export const userConstant = {
    REGISTER_REQUEST: 'FETCH_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'FETCH_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'FETCH_REGISTER_FAILURE',

    LOGIN_REQUEST: 'FETCH_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'FETCH_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'FETCH_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT'
}